version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: docker-monitor-backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - docker-monitor-data:/app/data
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - monitor-network
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: docker-monitor-frontend
    ports:
      - "4173:4173"
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL:-http://localhost:5000}
      - PUBLIC_SOCKET_URL=${PUBLIC_SOCKET_URL:-http://localhost:5000}
      - PUBLIC_REFRESH_INTERVAL=${PUBLIC_REFRESH_INTERVAL:-5000}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - monitor-network

networks:
  monitor-network:
    driver: bridge

volumes:
  docker-monitor-data:
    driver: local