version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: docker-monitor-backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - docker-monitor-data:/app/data
    ports:
      - "5000:5000"
    restart: always
    networks:
      - monitor-network
    environment:
      - PYTHONUNBUFFERED=1
      # Comentamos DOCKER_HOST para Windows, ya que puede causar problemas
      # - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/containers || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    # En Windows, no necesitamos privileged ni user root
    # privileged: true
    # user: root

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: docker-monitor-frontend
    ports:
      - "4173:4173"
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL:-http://localhost:5000}
      - PUBLIC_SOCKET_URL=${PUBLIC_SOCKET_URL:-http://localhost:5000}
      - PUBLIC_REFRESH_INTERVAL=${PUBLIC_REFRESH_INTERVAL:-5000}
    depends_on:
      - backend
    restart: always
    networks:
      - monitor-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:4173 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 256M

networks:
  monitor-network:
    driver: bridge

volumes:
  docker-monitor-data:
    driver: local