version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: docker-monitor-backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - docker-monitor-data:/app/data
    ports:
      - "5000:5000"
    restart: always
    networks:
      - monitor-network
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/containers"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: docker-monitor-frontend
    ports:
      - "4173:4173"
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL}
      - PUBLIC_SOCKET_URL=${PUBLIC_SOCKET_URL}
      - PUBLIC_REFRESH_INTERVAL=${PUBLIC_REFRESH_INTERVAL}
    depends_on:
      backend:
        condition: service_healthy
    restart: always
    networks:
      - monitor-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:4173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 256M

networks:
  monitor-network:
    driver: bridge

volumes:
  docker-monitor-data:
    driver: local